# Generated by Django 4.1.3 on 2023-01-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("R", models.FloatField(default=0.0)),
                ("Y", models.FloatField(default=0.0)),
                ("B", models.FloatField(default=0.0)),
                ("U", models.FloatField(default=0.0)),
                ("RC", models.FloatField(default=0.0)),
                ("YC", models.FloatField(default=0.0)),
                ("BC", models.FloatField(default=0.0)),
                ("UC", models.FloatField(default=0.0)),
                ("UB", models.FloatField(default=0.0)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
